export function shortenMatName(text) {
    const shortTable = {
        // Agricultural Products
        'All-Purpose Fodder': 'FOD',
        'Flowery Hops': 'HOP',
        'Caffeinated Beans': 'CAF',
        'High-Carb Grains': 'GRN',
        'High-Carb Maize': 'MAI',
        'Raw Cotton Fiber': 'RCO',
        'Triglyceride Nuts': 'NUT',
        'Triglyceride Fruits': 'VEG',
        'Wine-Quality Grapes': 'GRA',
        'Spicy Herbs': 'HER',
        'Hydrocarbon Plants': 'HCP',
        'Meat Tissue Patties': 'MTP',
        'Protein-Rich Mushrooms': 'MUS',
        'Pineberries': 'PIB',
        'Protein-Rich Algae': 'ALG',
        'Protein-Rich Beans': 'BEA',
        'Protein Paste': 'PPA',
        'Raw Silk Strains': 'RSI',
        'Vita Essence': 'VIT',

        // Alloys
        'Ferrominium': 'FAL',
        'Alpha-Stabilized Titanium': 'ASD',
        'Borosilicate': 'BOS',
        'Bronze': 'BRO',
        'Red Gold': 'RGO',
        'Blue Gold': 'BGO',
        'Ferro-Titanium': 'FET',
        'Alpha-Stabilized Tungsten': 'WAL',

        // Chemicals
        'Artificial Soil': 'SOI',
        'Helpful Bacteria': 'BAC',
        'Desaturation Agent': 'BLE',
        'Breathable Liquid': 'BL',
        'Chemical Reagents': 'REA',
        'Cryogenic Stabilizer': 'CST',
        'Enriched Einsteinium': 'EES',
        'Enriched Technetium': 'ETC',
        'Flux': 'FLX',
        'Indigo Colorant': 'IND',
        'Liquid Crystals': 'LCR',
        'Nano-Enhanced Resin': 'NR',
        'Nutrient Solution': 'NS',
        'Olfactory Substances': 'OLF',
        'DDT Plant Agent': 'DDT',
        'Premium Fertilizer': 'PFE',
        'Sedative Substance': 'JUI',
        'TCL Acid': 'TC',
        'ThermoFluid': 'THF',
        'Sodium Borohydride': 'NAB',

        // Construction Materials
        'Epoxy Resin': 'EPO',
        'InsuFoam': 'INS',
        'MegaTube Coating': 'MTC',
        'Mineral Construction Granulate': 'MCG',
        'Nano-Carbon Sheeting': 'NCX',
        'Nano Fiber': 'NFI',
        'Nano-Coated Glass': 'NG',
        'Reinforced Glass': 'RG',
        'Poly-Sulfite Sealant': 'SEA',
        'Glass': 'GL',

        // Construction Parts
        'Aerostat Foundation': 'AEF',
        'Air Scrubber': 'AIR',
        'Decorative Elements': 'DEC',
        'Floating Tank': 'FLO',
        'Flow Control Device': 'FC',
        'Fluid Piping': 'FLP',
        'Cylindrical Gas Container': 'GC',
        'Gas Vent': 'GV',
        'Magnetic Ground Cover': 'MGC',
        'Metal-Halide Lighting System': 'MHL',
        'Neon Lighting System': 'LIT',
        'Pressure Shielding': 'PSH',
        'Radiation Shielding': 'RSH',
        'Stabilized Technetium': 'TCS',
        'Thermal Shielding': 'TSH',
        'Truss': 'TRU',

        // Construction Prefabs
        'Advanced Bulkhead': 'ABH',
        'Advanced Deck Elements': 'ADE',
        'Advanced Structural Elements': 'ASE',
        'Advanced Transparent Aperture': 'ATA',
        'Basic Bulkhead': 'BBH',
        'Basic Deck Elements': 'BDE',
        'Basic Structural Elements': 'BSE',
        'Basic Transparent Aperture': 'BTA',
        'Hardened Structural Elements': 'HSE',
        'Lightweight Bulkhead': 'LBH',
        'Lightweight Deck Elements': 'LDE',
        'Lightweight Structural Elements': 'LSE',
        'Lightweight Transparent Aperture': 'LTA',
        'Reinforced Bulkhead': 'RBH',
        'Reinforced Deck Elements': 'RDE',
        'Reinforced Structural Elements': 'RSE',
        'Reinforced Transparent Aperture': 'RTA',

        // Consumables (basic)
        'Drinking Water': 'DW',
        'Smart Space Suit': 'HSS',
        'Flavoured Insta-Meal': 'FIM',
        'Personal Data Assistant': 'PDA',
        'Basic Overalls': 'OVE',
        'Basic Rations': 'RAT',
        'AI-Assisted Lab Coat': 'LC',
        'Quality Meat Meal': 'MEA',
        'Scientific Work Station': 'WS',
        'Exoskeleton Work Suit': 'EXO',
        'Power Tools': 'PT',
        'HazMat Work Suit': 'HMS',
        'Basic Medical Kit': 'MED',
        'Multi-Purpose Scanner': 'SCN',

        // Consumables (luxury)
        'Einsteinium-Infused Gin': 'GIN',
        'VitaGel': 'VG',
        'Padded Work Overall': 'PWO',
        'Caffeinated Infusion': 'COF',
        'Smart Zinfandel': 'WIN',
        'NeuroStimulants': 'NST',
        'Kombucha': 'KOM',
        'Repair Kit': 'REP',
        'Stellar Pale Ale': 'ALE',
        'Stem Cell Treatment': 'SC',

        // Drones
        'Crowd Control Drone': 'CCD',
        'Drone Chassis': 'DCH',
        'Drone Frame': 'DRF',
        'Rescue Drone': 'RED',
        'Ship-Repair Drone': 'SRD',
        'Surgical Drone': 'SDR',
        'Surveillance Drone': 'SUD',

        // Electronic Devices
        'Antenna Array': 'AAR',
        'Body Scanner': 'BSC',
        'Full-Body Interaction Device': 'BID',
        'Holographic Display': 'HD',
        'Holographic Glasses': 'HOG',
        'Basic Mainframe': 'BMF',
        'Micro Headphones': 'MHP',
        'Radio Device': 'RAD',
        'Sensor Array': 'SAR',
        'Handheld Personal Console': 'HPC',
        'Active Water Filter': 'AWF',
        'Basic Workstation': 'BWS',

        // Electronic Parts
        'Audio Transmitter': 'TRA',
        'Active Cooling Device': 'FAN',
        'Memory Bank': 'RAM',
        'Micro-Processor': 'MPC',
        'Motherboard': 'MB',
        'Non-Volatile Memory': 'ROM',
        'Printed Circuit Board': 'PCB',
        'Sensor': 'SEN',
        'Tensor Processing Unit': 'TPU',
        'Capacitive Display': 'CD',
        'Information Display': 'DIS',

        // Electronic Pieces
        'Shielded Connector': 'BGC',
        'Electric Field Capacitor': 'CAP',
        'Budget Connectors': 'BCO',
        'Medium Fastener Kit': 'MFK',
        'Small Fastener Kit': 'SFK',
        'Laser Diodes': 'LDI',
        'High-Capacity Connectors': 'HCC',
        'Advanced Transistor': 'TRN',
        'Medium Wafer': 'MWF',
        'Small Wafer': 'SWF',

        // Electronic Systems
        'Audio Distribution System': 'ADS',
        'Automated Cooling System': 'ACS',
        'Climate Controller': 'CC',
        'Communication System': 'COM',
        'Cryogenic Unit': 'CRU',
        'FTL Field Controller': 'FFC',
        'Life Support System': 'LIS',
        'Logistics System': 'LOG',
        'Stability Support System': 'STS',
        'Targeting Computer': 'TAC',
        'Water Reclaimer': 'WR',

        // Elements
        'Beryllium': 'BE',
        'Calcium': 'CA',
        'Carbon': 'C',
        'Chlorine': 'CL',
        'Einsteinium': 'ES',
        'Iodine': 'I',
        'Magnesium': 'MG',
        'Sodium': 'NA',
        'Sulfur': 'S',
        'Tantalum': 'TA',
        'Technetium': 'TC',
        'Zirconium': 'ZR',

        // Energy Systems
        'Large Capacitor Bank': 'CBL',
        'Medium Capacitor Bank': 'CBM',
        'Power Cell': 'POW',
        'Small Capacitor Bank': 'CBS',
        'Solar Cell': 'SOL',
        'Solar Panel': 'SP',

        // Fuels
        'FTL Fuel': 'FF',
        'STL Fuel': 'SF',

        // Gases
        'Ammonia': 'AMM',
        'Argon': 'AR',
        'Fluorine': 'F',
        'Helium': 'HE',
        'Helium-3 Isotope': 'HE3',
        'Hydrogen': 'H',
        'Neon': 'NE',
        'Nitrogen': 'N',
        'Oxygen': 'O',

        // Liquids
        'Heliotrope Extract': 'HEX',
        'Liquid Einsteinium': 'LES',
        'Bacterial Tungsten Solution': 'BTS',
        'Water': 'H2O',

        // Medical Equipment
        'Auto-Doc': 'ADR',
        'Bandages': 'BND',
        'Medical Stretcher': 'STR',
        'Painkillers': 'PK',
        'Surgical Equipment': 'SEQ',
        'Test Tubes': 'TUB',

        // Metals
        'Aluminium': 'AL',
        'Copper': 'CU',
        'Gold': 'AU',
        'Iron': 'FE',
        'Lithium': 'LI',
        'Silicon': 'SI',
        'Steel': 'STL',
        'Titanium': 'TI',
        'Tungsten': 'W',

        // Minerals
        'Beryl Crystals': 'BER',
        'Bioreactive Minerals': 'BRM',
        'Boron Crystals': 'BOR',
        'Caliche Rock': 'CLI',
        'Galerite Rock': 'GAL',
        'Halite Crystals': 'HAL',
        'Limestone': 'LST',
        'Magnesite': 'MGS',
        'Magnetite': 'MAG',
        'Sulfur Crystals': 'SCR',
        'Tantalite Rock': 'TAI',
        'Technetium Oxide': 'TCO',
        'Tectosilisite': 'TS',
        'Zircon Crystals': 'ZIR',

        // Ores
        'Aluminium Ore': 'ALO',
        'Copper Ore': 'CUO',
        'Gold Ore': 'AUO',
        'Iron Ore': 'FEO',
        'Lithium Ore': 'LIO',
        'Silicon Ore': 'SIO',
        'Titanium Ore': 'TIO',

        // Plastics
        'Durable Casing L': 'DCL',
        'Polymer Sheet Type L': 'PSL',
        'Durable Casing M': 'DCM',
        'Polymer Sheet Type M': 'PSM',
        'Poly-Ethylene': 'PE',
        'Polymer Granulate': 'PG',
        'Durable Casing S': 'DCS',
        'Polymer Sheet Type S': 'PSS',

        // Ship Engines
        'Advanced STL Engine': 'AEN',
        'Advanced Fuel Pump': 'AFP',
        'Advanced Fuel Rod': 'AFR',
        'Advanced Nozzle': 'ANZ',
        'Basic Fuel Pump': 'BFP',
        'Basic Fuel Rod': 'BFR',
        'Basic Nozzle': 'NOZ',
        'Combustion Chamber': 'CHA',
        'Fission Reactor': 'FIR',
        'Fuel-saving STL Engine': 'PSE',
        'Glass Combustion Chamber': 'GCH',
        'Glass-based STL Engine': 'GEN',
        'Glass Nozzle': 'GNZ',
        'High-power FTL Reactor': 'HPR',
        'Hyper-power Reactor': 'HYR',
        'Hyperthrust STL Engine': 'HTE',
        'Hyperthrust Nozzle': 'HNZ',
        'Large FTL Emitter': 'LFE',
        'Low-heat Fuel Pump': 'LFP',
        'Medium FTL Emitter': 'MFE',
        'Quick-charge FTL Reactor': 'QCR',
        'Radioisotope Generator': 'RAG',
        'Reactor Control System': 'RCS',
        'Small FTL Emitter': 'SFE',
        'Standard STL Engine': 'ENG',
        'Standard FTL Reactor': 'RCT',

        // Ship Kits
        'High-load Cargo Bay Kit': 'WCB',
        'High-volume Cargo Bay Kit': 'VCB',
        'Large Cargo Bay Kit': 'LCB',
        'Large FTL Fuel Tank Kit': 'LFL',
        'Large STL Fuel Tank Kit': 'LSL',
        'Medium Cargo Bay Kit': 'MCB',
        'Medium FTL Fuel Tank Kit': 'MFL',
        'Medium STL Fuel Tank Kit': 'MSL',
        'Small Cargo Bay Kit': 'SCB',
        'Small FTL Fuel Tank Kit': 'SFL',
        'Small STL Fuel Tank Kit': 'SSL',
        'Tiny Cargo Bay Kit': 'TCB',
        'Very Small Cargo Bay Kit': 'VSC',

        // Ship Parts
        'Advanced High-G Seats': 'AGS',
        'Advanced Hull Plate': 'AHP',
        'Advanced Thermal Protection Material': 'ATP',
        'Basic High-G Seats': 'BGS',
        'Basic Hull Plate': 'BHP',
        'Basic Thermal Protection Material': 'THP',
        'Hardened Hull Plate': 'HHP',
        'Lightweight Hull Plate': 'LHP',
        'Navigation Module MK1': 'NV1',
        'Navigation Module MK2': 'NV2',
        'Reinforced Hull Plate': 'RHP',
        'Structural Spacecraft Component': 'SSC',

        // Ship Shields
        'Advanced Thermal Protection Tile': 'APT',
        'Advanced Anti-rad Plate': 'ARP',
        'Advanced Whipple Shielding': 'AWH',
        'Basic Thermal Protection Tile': 'BPT',
        'Basic Anti-rad Plate': 'BRP',
        'Basic Whipple Shielding': 'BWH',
        'Specialized Anti-rad Plate': 'SRP',

        // Software Components
        'Basic AI Framework': 'BAI',
        'Local Database': 'LD',
        'Machine Learning Interface': 'MLI',
        'Networking Framework': 'NF',
        'Search Algorithm': 'SA',
        'Sorting Algorithm': 'SAL',
        'Window Manager': 'WM',

        // Software Systems
        'Information Data Core': 'IDC',
        'Information Management System': 'IMM',
        'Spatial Navigation Map': 'SNM',
        'Weak Artificial Intelligence': 'WAI',

        // Software Tools
        'Data Analyzer': 'DA',
        'Data Visualizer': 'DV',
        'Distributed Database': 'DD',
        'Entertainment Data core': 'EDC',
        'Neural Network': 'NN',
        'Operating System': 'OS',

        // Textiles
        'Ceramic Fabric': 'CF',
        'Ceramic-Tungsten Fabric': 'CTF',
        'Cotton Fabric': 'COT',
        'Kevlar Fabric': 'KV',
        'Nylon Fabric': 'NL',
        'Silken Fabric': 'SIL',
        'TechnoKevlar Fabric': 'TK',

        // Unit Prefabs
        'Command Bridge MK1': 'BR1',
        'Command Bridge MK2': 'BR2',
        'Short-distance Command Bridge': 'BRS',
        'Crew Quarters (Large)': 'CQL',
        'Crew Quarters (Medium)': 'CQM',
        'Crew Quarters (Small)': 'CQS',
        'Crew Quarters (Tiny)': 'CQT',
        'Drone Operations Unit': 'DOU',
        'Entertainment Unit': 'FUN',
        'Habitat Unit': 'HAB',
        'Handcraft Workshop Unit': 'WOR',
        'Laboratory Unit': 'LU',
        'Large Ship-Repair Drone Operations Unit': 'RDL',
        'Small Ship-Repair Drone Operations Unit': 'RDS',
        'Surgery Unit': 'SU',
        'Trauma Care Unit': 'TCU',

        // Utility
        'Office Supplies': 'OFF',
        'Safety Uniform': 'SUN',
        'Universal Toolset': 'UTS',

        // misc
        'Core Module Kit': 'CMK',
    }

    return shortTable[text] || text;
}